### ISSUE TITLE
The check box in "ADC Easy View diagram" could not show correct config settings

### ISSUE THREAD

**Issue by librachien** [Microchip-MPLAB-Harmony/mhc#1]
While reopening MHC, all the settings of check box in ADC Easy View diagram will miss.
It seems ADC Easy View diagram check box cannot parser correct settings from configuration file.
But the all the variable or pull-down selection menu are correct.
I am using SAMD21G18A with latest MH3.

**Comment by aethaniel** [comment]
@librachien thanks for reporting, we are investigating.

**Comment by dineshvedium** [comment]
Hi @librachien , 
Can you update your local harmony repositories and test it. Because, we tested with latest repositories, its working fine.
