### ISSUE TITLE
Cannot start on Windows the MHC if the user home directory contains UTF accented characters

### ISSUE THREAD

**Issue by SandorDobi** [Microchip-MPLAB-Harmony/mhc#11]
Hi
If the Windows username contains accented characters and by default the home directory path will contains this characters too, then the MHC when start building a initial database, will throw a pyton exception like
"UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 20: ordinal not in range(128)" the concrete character code is depends on the character which is in the path. 

When I moved the home folder to another path without accented characters the MHC was succesfully built the database and started up.

**Comment by aethaniel** [comment]
Thanks for reporting. We are processing it through internal ticket MH3-36411

**Comment by aethaniel** [comment]
Fixed and delivered as part of MHC v3.4.1
