### ISSUE TITLE
File generation stuck at ...\gac_source.c.ftl

### ISSUE THREAD

**Issue by LuisCRSousa** [Microchip-MPLAB-Harmony/mhc#14]
Just updated mhc to 3.4.0 and it gets stucks at 99% at ...aria\library\plugins\gac_source.c.ftl

**Comment by LuisCRSousa** [comment]
`<Generate>[Info]: Processing file: "C:\Users\X\Harmony3\gfx\middleware\aria\library\plugins\gac_source.c.ftl"
<Generate>[Info]: An exception occured during state processing.
<Log>[Error]: Exception cause: java.lang.NullPointerException: Security flag can't be null
<MHC>[Info]: Stack trace filtered due to currently set log level.  See "C:\Users\X\.mh3\mhc.log" for full details.
<MHC>[Info]: To change log level filter see Tools->Options->Harmony in MPLABX
<Generate>[Error]: Aborting project generation.  Your project has not been modified.
<Manifest>[Info]: Manifest info has been written in file : C:\Users\X\MPLABXProjects\X\firmware\src\config\X\harmony-manifest-failure.yml
<Event>[Info]: Broadcasting event: OptionsModifiedEvent - 
<Event>[Info]: Broadcasting event: OptionsModifiedEvent - 
<Event>[Info]: Broadcasting event: OptionsModifiedEvent - 
<Event>[Info]: Broadcasting event: OptionsModifiedEvent - 
<Event>[Info]: Broadcasting event: OptionsModifiedEvent - 
<Event>[Info]: Broadcasting event: OptionsModifiedEvent - 
<Event>[Info]: Broadcasting event: OptionsModifiedEvent - 
<Event>[Info]: Broadcasting event: OptionsModifiedEvent - 
<Event>[Info]: Broadcasting event: OptionsModifiedEvent - 
<Event>[Info]: Broadcasting event: OptionsModifiedEvent - 
<Event>[Info]: Broadcasting event: OptionsModifiedEvent - `

**Comment by LuisCRSousa** [comment]
`
# This file has been autogenerated by MPLAB Harmony Configurator. Please do not edit this file.
# Project "fw_xcoredisplay" has been created by using mentioned Harmony 3 packages


project: X
creation_date: 2020-05-22T14:55:57.960+01:00[Europe/London]    # ISO 8601 format: https://www.w3.org/TR/NOTE-datetime
operating_system: Windows 10
mhc_mode: IDE            # [IDE|Standalone|Headless]
mplabx_version: v5.40        # if MPLAB X plugin only
plugin_version: v3.5.0        # if MPLAB X plugin only

modules:
    - {name: "bsp", version: "v3.7.0"}
    - {name: "contentmanager", version: "v1.3.1"}
    - {name: "core", version: "v3.7.1"}
    - {name: "csp", version: "v3.7.1"}
    - {name: "dev_packs", version: "v3.6.1"}
    - {name: "gfx", version: "v3.6.0"}
    - {name: "mhc", version: "v3.4.0"}
    - {name: "touch", version: "v3.6.0"}
    - {name: "usb", version: "v3.5.0"}
`

**Comment by kkathirvel** [comment]
can you please attach the log file?

C:\Users\<user_name>\.mh3\mhc.log

**Comment by LuisCRSousa** [comment]
[mhc.log](https://github.com/Microchip-MPLAB-Harmony/mhc/files/4668785/mhc.log)
 File attached.

This should be what you are looking for:
`<Generate>[Info]: Processing file: "C:\Users\luisc\Harmony3\gfx\middleware\aria\library\plugins\gac_source.c.ftl"
<Generate>[Info]: An exception occured during state processing.
<Log>[Error]: Exception cause: java.lang.NullPointerException: Security flag can't be null`

**Comment by MHGC** [comment]
Hi,

Can you try replacing the attached .jar files in following locations, relaunch MHC and regenerate?
gfx\middleware\aria\library\plugins\libaria.jar
gfx\middleware\aria\library\plugins\lib\gac.jar

The Display Manager will require a replacement .jar file to work with MHC v3.4.0 also:
gfx\middleware\aria\hal\plugins\displaymanager.jar

Please let me know if this works for you or not.

[plugins.zip](https://github.com/Microchip-MPLAB-Harmony/mhc/files/4670689/plugins.zip)

**Comment by LuisCRSousa** [comment]
It worked :) Thanks!

**Comment by joeostrander** [comment]
This fixed 2 issues I had:
1) NullPointerException on code generation
2) Could not add new Fonts with Graphics Composer (Aria)

Thank you!

**Comment by LuisCRSousa** [comment]
This issue is still present in the current mhc version
