### ISSUE TITLE
Generated file app.h has elemets outside include guards

### ISSUE THREAD

**Issue by JPortici** [Microchip-MPLAB-Harmony/mhc#15]
mhc package version 3.4.0
device PIC32MK1024GPE100

Let's create a new project and generate the source files with default settings.
The "app.c" file has the

#ifdef __cplusplus
}
#endif

after the include guards

**Comment by vishalnxt** [comment]
@JPortici , thanks for reporting the issue. I am filing an internal ticket and will be resolved in the next release.
