### ISSUE TITLE
Generate failing after project migration to MHC v3.6.0

### ISSUE THREAD

**Issue by vitalEol** [Microchip-MPLAB-Harmony/mhc#16]
After migrating my project from MHC v3.5.1 to the latest v3.6.0 I'm unable to update my configuration - the generate code option fails with a java exception
![image](https://user-images.githubusercontent.com/42639787/96996326-930de000-1527-11eb-8dbd-85744a643df4.png)

My previous branch of the project using MHC v3.5.1 still works - I can Generate/Merge/Build/Debug my project using Mplab-X v5.40 without encountering the java exception

**Comment by sandeepm1** [comment]
Hi,

Graphic library is not compatible with the new version of MHC 3.6.0.  Graphic may soon release a patch version to make it compatible. 
If you open your existing project with new version of MHC 3.6.0  the mhc configuration format will get updated to new yml format. The configurations settings are now saved in <configuration name>.mhc folder in yml format. 
The existing <configuration name>.xml file will get renamed to <configuration name>.xml.backup and harmony.prj will get renamed to harmony.prj.backup.
To open this project again with MHC version 3.5.1 you can remove the ".backup" extension from both files.
