### ISSUE TITLE
Add support for GCC

### ISSUE THREAD

**Issue by JakeSays** [Microchip-MPLAB-Harmony/mhc#18]
Currently MHC only supports XC32, KEIL, and IAR while MPLAB X supports those and GCC.

Please add support for GCC.

**Comment by pustekuchen91** [comment]
+1 we are using gcc-arm-none-eabi. it would be nice if you support this.

**Comment by aethaniel** [comment]
Hi @JakeSays , @pustekuchen91 , this request has been pushed to Harmony management. We don't know when or if this support will be brought.

**Comment by pustekuchen91** [comment]
Hi @aethaniel, 
thanks for the respone.
