### ISSUE TITLE
MHC launches diff tool but file has not differences

### ISSUE THREAD

**Issue by djsaz** [Microchip-MPLAB-Harmony/mhc#2]
When I regenerate the UART app for the A5D2 I get several files pop up in the diff tool even though they don’t actually have any differences.  If no diff tool is configured in MHC then MHC will throw an exception and fail to generate the code.

**Comment by zzelevl** [comment]
We will address this for next release, but for now, there are two workarounds:

1.	Configure MHC to use diff tool:
      a.	Select File > Preferences from the menu.
      b.	Enter the pathname to the executable file for your preferred "diff" tool and click Close. (Pass command line arguments as {0} {1} e.g. C:\difftool\difftool.exe {0} {1} )
2.	During code generation, select an option for MHC to accept all generated changes.
