### ISSUE TITLE
MHC changing YML files at each save

### ISSUE THREAD

**Issue by KonssnoK** [Microchip-MPLAB-Harmony/mhc#21]
(Using latest released version)
This is something quite annoying when you track the YML files in a repository.

Basically, you don't have to do anything else than regenerating the code or changing one setting to have 20+ files modified.
Looking at the changes, they are completely unrelated to what you touched inside the configurator.

I guess the files are not generated in a structured way but in a random one, where nodes are added in a non consistent way, mixing order. Sometimes there are also properties appearing/disappearing depending on the generation...

example:

I enabled the INCLUDE_xTaskGetSchedulerState functionality to FreeRTOS, NOTHING ELSE.

Code changed:
![image](https://user-images.githubusercontent.com/10288926/111022265-011d4b80-83d2-11eb-996e-aeb64ebc93a0.png)

YML changes examples ( 21 files! ):

![image](https://user-images.githubusercontent.com/10288926/111022336-7ee15700-83d2-11eb-9417-bb4fe59e6146.png)
![image](https://user-images.githubusercontent.com/10288926/111022350-8c96dc80-83d2-11eb-88b8-4b53f953023f.png)
![image](https://user-images.githubusercontent.com/10288926/111022359-991b3500-83d2-11eb-8af5-51e9467d5515.png)

**Comment by sandeepm1** [comment]
Hi,
Thanks for posting, this is known issue and we are working on this. However, this should not impact the generated files. 
Regards

**Comment by KonssnoK** [comment]
Hi sanddeep, yes, this does not impact generated files.
Good to know it's under investigation :)

**Comment by KonssnoK** [comment]
This issue should have been fixed, closing for now
