### ISSUE TITLE
MHC not keeping link between SDCard and SPI Driver

### ISSUE THREAD

**Issue by KonssnoK** [Microchip-MPLAB-Harmony/mhc#22]
Let's start by saying that i don't know exactly how to replicate. It happens most of the times but not always.

Steps:

Generate a SD Card handler in MHC, link it to a SPI driver/SPI peripheral.
![image](https://user-images.githubusercontent.com/10288926/111875936-8c7f7980-899c-11eb-997f-3a81a038e268.png)

Save/Generate code
Close MHC. (Maybe close MPLab?)

Reopen the same project, this is what will be seen.

![image](https://user-images.githubusercontent.com/10288926/111875897-68bc3380-899c-11eb-98bd-21def9cc98dc.png)

The link between the 2 blocks is lost for no apparent reason.

**Comment by sandeepm1** [comment]
@KonssnoK  Thanks for reporting this issue. I have raised an internal ticket to investigate this.

**Comment by KonssnoK** [comment]
@sandeepm1 news?

**Comment by KonssnoK** [comment]
closing after 3 years of nothing to remove it from my board
