### ISSUE TITLE
MHC not generating vector code for Timer1

### ISSUE THREAD

**Issue by KonssnoK** [Microchip-MPLAB-Harmony/mhc#23]
This is a bit of a strange issue.

The PIC32MZ vector 4 is dedicated to the timer1 handler.
In MHC it's clearly stated that the Timer1 interrupt should generate the code for TIMER_1_Handler.
![image](https://user-images.githubusercontent.com/10288926/111876084-5abae280-899d-11eb-9108-c4bc63ff27fb.png)
Such code is not generated and there is no way to know why it is not generated.

By manually implementing the vector handler i discovered that such vector is automatically dedicated to the FreeRTOS sys_tick handler, which seems not overridable.

It would be nice to have some kind of warning or note indicating that the vector will not be generated (contrary to what it's visible in the picture).

Also priorities are ignored, so it's impossible to change timer 1 priorities.

**Comment by vishalnxt** [comment]
@KonssnoK , Thank you for reporting the issue.  As you pointed out, Timer 1 (which is used as kernel tick) is completely managed/configured by the FreeRTOS source code. FreeRTOS sets the Timer1 priority based on the Kernel Interrupt Priority configured under the FreeRTOS configuration. 
We have filed an internal ticket to indicate that the Timer 1 is used by FreeRTOS and hence will not be available for the application.
