### ISSUE TITLE
Graphics Composer always exporting screen even when generate is not checked

### ISSUE THREAD

**Issue by LuisCRSousa** [Microchip-MPLAB-Harmony/mhc#7]
Graphics Composer always exporting screen even when generate checkbox is not checked.
This is anoying because I have  lot of screens just to generate layout templates and they are exported and should not be.

I'm using the lastest libs at this date.

**Comment by MHGC** [comment]
Hi,
Which graphics library are you using?  Aria or Legato?  Aria and Legato uses different Composer plugin.  This helps us isolate.  Also, can you post a screenshot of what you are seeing?

**Comment by LuisCRSousa** [comment]
I'm using Aria. Latest libs. Actually I noticed this problem since the beginings of harmony 3.
I disable the generate checkbox but the screen is still being generated under libaria_init.

![Untitled](https://user-images.githubusercontent.com/8472158/69650872-26643a00-1067-11ea-8b64-aaefe1d56760.png)

**Comment by MHGC** [comment]
Replace libaria.jar with the one here.  Give it a try and see it it works for you.

[libaria.zip](https://github.com/Microchip-MPLAB-Harmony/mhc/files/3893091/libaria.zip)

**Comment by MHGC** [comment]
Replace under gfx\middleware\aria\library\plugins

**Comment by LuisCRSousa** [comment]
It worked :) Thanks a lot.

Will you update harmony with this libaria version?

**Comment by MHGC** [comment]
Most certainly.  It will be in v3.6.0 (estimate Feb/March)
